// MSGS.ERROR
// MSGS.COMMON_FORM_BACK
// MSGS.COMMON_Close
// MSGS.COMMON_FORM_BACK
// MSGS.COMMON_CHANGES_SAVED
// MSGS.COMMON_BTN_Continue
// MSGS.ADMIN_TOOLS

// MSGS.IMPAREA_HPT
// MSGS.IMPAREA_NTD
// MSGS.IMPAREA_EGOAL
// MSGS.IMPAREA_EDATA
// MSGS.IMPAREA_ECARD
// MSGS.IMPAREA_QC
// MSGS.IMPAREA_LA
// MSGS.IMPAREA_GMF
// MSGS.IMPAREA_PMF
// MSGS.IMPAREA_VPF
// MSGS.IMPAREA_CMF
// MSGS.IMPAREA_JEP
// MSGS.IMPAREA_UAM
// MSGS.IMPAREA_WA
// MSGS.IMPAREA_TOFF
// MSGS.IMPAREA_CS
// MSGS.IMPAREA_FR
// MSGS.IMPAREA_DT
// MSGS.IMPAREA_OB
// MSGS.IMPAREA_OBACT
// MSGS.IMPAREA_BUIS
// MSGS.IMPAREA_JR
// MSGS.IMPAREA_SB
// MSGS.IMPAREA_AMA
// MSGS.IMPAREA_CD
// MSGS.IMPAREA_JGRP
// MSGS.IMPAREA_SWPA

// MSGS.MODULE_ECT
// MSGS.MODULE_GM
// MSGS.MODULE_CALIBRATION
// MSGS.MODULE_TFT
// MSGS.MODULE_HP
// MSGS.MODULE_ANALYTICS
// MSGS.MODULE_LMS
// MSGS.MODULE_OB
// MSGS.MODULE_SM
// MSGS.MODULE_JAM
// MSGS.MODULE_PMTFT
// MSGS.MODULE_COMP
// MSGS.MODULE_VP
// MSGS.MODULE_EQC
// MSGS.MODULE_RCM
// MSGS.MODULE_ORG
// MSGS.MODULE_EQ
// MSGS.MODULE_TF
// MSGS.MODULE_CDP

// MSGS.SEF_EVENT_CENTER
// MSGS.SEF_EVENT_CENTER_DETAIL_DESC
// MSGS.SEF_GO_TO_EVENT_MONITOR
// MSGS.SEF_GO_TO_EVENT_CENTER
// MSGS.SEF_EVENT_TYPE
// MSGS.SEF_EVENT_LIST
// MSGS.SEF_EVENT_NO_DESCRIPTION
// MSGS.SEF_STATUS_NO_XM_PERMISSION

// MSGS.SEF_EVENT_DETAIL

// MSGS.SEF_EVENT_MONITORING
// MSGS.SEF_EVENT_MONITORING_TITLE

// MSGS.SEF_EVENT_PUBLISHER
// MSGS.SEF_PUBLISHER_DETAIL_VIEW_PUBLISHING_RULE_LABEL
// MSGS.SEF_PUBLISHER_DETAIL_CONFIG_EXTERNAL_ENDPOINT_LABEL

// MSGS.SEF_EVENT_NOTIFICATIONS
// MSGS.SEF_EVENT_NOTIFICATIONS_SUBTITLE
// MSGS.SEF_EVENT_NOTIFICATIONS_PUSH
// MSGS.SEF_EVENT_NOTIFICATIONS_WEB
// MSGS.SEF_EVENT_NOTIFICATIONS_TODO
// MSGS.SEF_EVENT_NOTIFICATIONS_EMAIL
// MSGS.SEF_EVENT_NOTIFICATIONS_RECIPIENT_TYPE
// MSGS.SEF_EVENT_NOTIFICATIONS_TEMPLATE
// MSGS.SEF_EVENT_NOTIFICATIONS_NODATA_MSG
// MSGS.SEF_EVENT_NOTIFICATIONS_SHOW_TEMPLATES

// MSGS.SEF_EVENT_SUBSCRIBERS
// MSGS.SEF_EVENT_SUBSCRIBER
// MSGS.SEF_EVENT_PREPROCESSING_BEHAVIOR
// MSGS.SEF_EVENT_PREPROCESSING_BEHAVIOR_DAYS_VALIDATION_TEXT
// MSGS.SEF_EVENT_PREPROCESSING_BEHAVIOR_LABEL_1
// MSGS.SEF_EVENT_PREPROCESSING_BEHAVIOR_LABEL_2
// MSGS.SEF_EVENT_IMPACT_AREAS

// MSGS.SEF_EVENT_MONITOR
// MSGS.SEF_EVENT_RAISED
// MSGS.SEF_EVENT_RAISED_COUNT
// MSGS.SEF_EVENT_RAISED_DESC
// MSGS.SEF_EVENT_RAISED_NO_DATA
// MSGS.SEF_EVENT_RAISED_TIMEFRAME
// MSGS.SEF_EVENT_RAISED_TIMEFRAME_DAY
// MSGS.SEF_EVENT_RAISED_TIMEFRAME_WEEK
// MSGS.SEF_EVENT_RAISED_TIMEFRAME_MONTH
// MSGS.SEF_EVENT_RAISED_NOTE

// MSGS.SEF_EXTERNALLINK_ALERT_TITLE
// MSGS.SEF_EXTERNALLINK_ALERT_DIALOG
// MSGS.SEF_EXTERNALLINK_ALERT_DESC
